### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by weijunfeng** [ttypic/swift-klib-plugin#15]
Also, consider filing an issue with full Gradle log here: https://kotl.in/issue
The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
output:
-iphoneos_version_min has been renamed to -ios_version_min
ld: warning: passed two min versions (9.0, 13.0) for platform iOS. Using 13.0.
ld: unknown options: -sdk_version 

FAILURE: Build failed with an exception.

**Comment by ttypic** [comment]
Hi @weijunfeng ! Could you please provide more details?

**Comment by kalinjul** [comment]
I have a related problem using XCode 15:
`2023-11-14T19:57:54.969+0100 [ERROR] [system.err] The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
2023-11-14T19:57:54.969+0100 [ERROR] [system.err] output:
2023-11-14T19:57:54.969+0100 [ERROR] [system.err] ld: unknown options: -ios_simulator_version_min 
`

It seems that -ios_simulator_version_min is no longer available and may have been replaced by -platform_version

**Comment by ttypic** [comment]
@kalinjul thank you very much for looking into this and creating PR! 

Hi @weijunfeng, could check the latest version of plugin? Problem should be resolved, just double check that you are using Kotlin 1.9.10+

**Comment by weijunfeng** [comment]
it is very good
