### ISSUE TITLE
Testing Locally

### ISSUE THREAD

**Issue by hartbit** [ttypic/swift-klib-plugin#21]
In an attempt to debug a problem I'm having using Swift Klib, and upload a pull request to fix it, I'd like to test the plugin locally. Do you have a procedure to do that ?

**Comment by IlyaGulya** [comment]
@hartbit any time you would like to test some changes to any plugin locally, you can call
`./gradlew publishToMavenLocal` and then use `mavenLocal()` repository in your project to test your changes locally.

**Comment by IlyaGulya** [comment]
Closing this issue for now. Feel free to reopen if you will have any other questions.
