### ISSUE TITLE
CryptoSwift is not working.

### ISSUE THREAD

**Issue by aadeshmindtickle** [ttypic/swift-klib-plugin#22]
I tried the steps for CryptoKit was working fine; but when I tried to use apis which made me import CryptoSwift it gave me error as

```
error: no such module 'CryptoSwift'
import CryptoSwift
```

**Comment by ttypic** [comment]
Hey @aadeshmindtickle,  unfortunately right now, it's impossible to import 3rd party libraries, plugin works only with built-in frameworks

**Comment by IlyaGulya** [comment]
Please track this issue instead: https://github.com/ttypic/swift-klib-plugin/issues/37
