### ISSUE TITLE
Cant't seem to build if the path of the KMM project has spaces

### ISSUE THREAD

**Issue by ahmadmssm** [ttypic/swift-klib-plugin#26]
What went wrong:
A problem was found with the configuration of task ':core:swiftklibNetworkUtilsImplIosArm64' (type 'CompileSwiftTask'). In plugin 'io.github.ttypic.swiftklib' type 'io.github.ttypic.swiftklib.gradle.task.CompileSwiftTask' property 'pathProperty' specifies directory 'xxxxx' which doesn't exist.

If the path of the KMM project has any folder with spaces, like `~/XYZ ABC/path` the space of the path isn't skipped and it fails to build because can't read the folder containing the swift file..

**Comment by IlyaGulya** [comment]
@ahmadmssm this should be fixed in https://github.com/ttypic/swift-klib-plugin/releases/tag/v0.6.3

**Comment by IlyaGulya** [comment]
Feel free to reopen if this issue persists
