### ISSUE TITLE
impossible sync with new wizard template

### ISSUE THREAD

**Issue by elviss116** [ttypic/swift-klib-plugin#28]
Hi, I can't sync my project after add your plugin: 

`

import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {

    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.jetbrainsCompose)
    //alias(libs.plugins.klibPlugin)
    id("io.github.ttypic.swiftklib") version "0.5.1"
}

kotlin {
    androidTarget {
        compilations.all {
            kotlinOptions {
                jvmTarget = "11"
            }
        }
    }
    
    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }
    
    sourceSets {
        
        androidMain.dependencies {
            implementation(libs.compose.ui.tooling.preview)
            implementation(libs.androidx.activity.compose)
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
        }
    }
}

android {
    namespace = "org.kmp.klib.plugin"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
    sourceSets["main"].res.srcDirs("src/androidMain/res")
    sourceSets["main"].resources.srcDirs("src/commonMain/resources")

    defaultConfig {
        applicationId = "org.kmp.klib.plugin"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "1.0"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    dependencies {
        debugImplementation(libs.compose.ui.tooling)
    }
}

`

error:

`
* What went wrong:
Script compilation errors:

  Line 13:     androidTarget {
               ^ Unresolved reference: androidTarget

  Line 14:         compilations.all {
                   ^ Unresolved reference: compilations

  Line 15:             kotlinOptions {
                       ^ Unresolved reference: kotlinOptions

  Line 16:                 jvmTarget = "11"
                           ^ Unresolved reference: jvmTarget

  Line 34:         androidMain.dependencies {
                   ^ Unresolved reference: androidMain`

**Comment by ttypic** [comment]
Hey @elviss116, 

Thanks for raising this! Could you please double-check whether the issues disappear after removing the swiftklib plugin? The errors you provided don't seem relevant to the plugin.

**Comment by mohamad-abuzaid** [comment]
Any fix for this?... I am facing same issue

**Comment by IlyaGulya** [comment]
@mohamad-abuzaid @phatblat 
Please test the 0.6.2 release of the plugin. 
This issue should be fixed now.

**Comment by IlyaGulya** [comment]
Closing this issue for now. Feel free to reopen if issue persists
