### ISSUE TITLE
Getting error on Import - Stripe

### ISSUE THREAD

**Issue by abdulbasithqb** [ttypic/swift-klib-plugin#36]
import Stripe
       ^
error: fatalError
fatalError
> Task :shared:swiftklibCoreStripeSDKIosSimulatorArm64 FAILED

Hi Can someone please help me to resolve this issue ?

**Comment by abdulbasithqb** [comment]
@IlyaGulya do you have any idea about this issue, i was trying integrate stripe sdk in kmm and native ios

**Comment by IlyaGulya** [comment]
> @IlyaGulya do you have any idea about this issue?, i was trying integrate stripe sdk in kmm and native ios

Hi!
Unfortunately, this plugin does not support using external dependencies at the moment.
That's on the roadmap but it's quite an issue to think about 🙂

**Comment by IlyaGulya** [comment]
Closing in favor of https://github.com/ttypic/swift-klib-plugin/issues/37
